using System;
using System.Drawing;
using System.IO;
using System.Net;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using Veles.Core;

namespace Veles.BuildPublisher
{
    internal static class Program
    {
        [STAThread]
        private static void Main() { ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12; Application.EnableVisualStyles(); Application.SetCompatibleTextRenderingDefault(false); Application.Run(new PublisherForm()); }
    }

    internal sealed class PublisherForm : Form
    {
        private TextBox _zip, _token, _name, _version, _minecraft, _loader, _loaderVersion, _ip, _port, _serverName, _site, _launchCommand;
        private Label _status;
        private Button _publish;
        private string _selectedZip;
        private readonly Color Orange = Color.FromArgb(255, 122, 25);
        public PublisherForm()
        {
            Text = "Veles Build Publisher"; Width = 760; Height = 760; MinimumSize = new Size(700, 650); BackColor = Color.FromArgb(16, 11, 8); ForeColor = Color.FromArgb(245, 238, 232); StartPosition = FormStartPosition.CenterScreen; BuildUi();
        }
        private void BuildUi()
        {
            var root = new Panel { Dock = DockStyle.Fill, Padding = new Padding(28), AutoScroll = true }; Controls.Add(root);
            root.Controls.Add(Label("V  VELES BUILD PUBLISHER", 0, 0, 15, FontStyle.Bold, Color.White)); root.Controls.Add(Label("Публикация сборки в kutsandriy14-cyber/veles-modpack-releases", 2, 27, 9, FontStyle.Regular, Color.FromArgb(163, 149, 141)));
            root.Controls.Add(Label("НОВАЯ СБОРКА СЕРВЕРА", 0, 70, 10, FontStyle.Bold, Orange));
            _zip = Text("", 0, 110, 535); _zip.ReadOnly = true; var choose = Button("Выбрать ZIP", 550, 108, 120, Orange, Color.Black); choose.Click += (s, e) => ChooseZip(); root.Controls.Add(Label("Архив готовой сборки", 0, 91, 9, FontStyle.Regular, Color.FromArgb(200, 184, 173))); root.Controls.Add(_zip); root.Controls.Add(choose);
            _name = AddField(root, "Название сборки", "TerraFirmaGreg: Modern", 0, 155); _version = AddField(root, "Версия сборки", "0.12.7", 340, 155); _minecraft = AddField(root, "Версия Minecraft", "1.20.1", 0, 220); _loader = AddField(root, "Модлоадер", "Forge", 340, 220); _loaderVersion = AddField(root, "Версия модлоадера", "47.2.0", 0, 285); _ip = AddField(root, "IP сервера", "213.152.43.53", 340, 285); _port = AddField(root, "Порт", "25589", 0, 350); _serverName = AddField(root, "Название сервера", "Veles PlayGame", 340, 350); _site = AddField(root, "Сайт", "https://veles-saite.vercel.app/", 0, 415); _launchCommand = AddField(root, "Команда запуска в ZIP", "start.bat", 340, 415);
            root.Controls.Add(Label("GITHUB ДОСТУП", 0, 485, 10, FontStyle.Bold, Orange)); root.Controls.Add(Label("Токен используется только в памяти во время публикации и не сохраняется.", 0, 508, 9, FontStyle.Regular, Color.FromArgb(163, 149, 141))); _token = Text("", 0, 535, 670); _token.UseSystemPasswordChar = true; root.Controls.Add(_token);
            _publish = Button("Создать релиз и загрузить build.zip + build-info.txt", 0, 590, 670, Orange, Color.Black); _publish.Height = 38; _publish.Click += async (s, e) => await PublishAsync(); root.Controls.Add(_publish); _status = Label("Готово к публикации", 0, 644, 10, FontStyle.Regular, Color.FromArgb(163, 149, 141)); root.Controls.Add(_status);
        }
        private TextBox AddField(Control parent, string caption, string value, int x, int y) { parent.Controls.Add(Label(caption, x, y, 9, FontStyle.Regular, Color.FromArgb(200, 184, 173))); var box = Text(value, x, y + 19, 315); parent.Controls.Add(box); return box; }
        private void ChooseZip()
        {
            using (var dialog = new OpenFileDialog { Filter = "ZIP archive (*.zip)|*.zip", Title = "Выберите архив сборки" }) if (dialog.ShowDialog(this) == DialogResult.OK) { _selectedZip = dialog.FileName; _zip.Text = Path.GetFileName(_selectedZip); _status.Text = "Архив выбран."; }
        }
        private async Task PublishAsync()
        {
            if (string.IsNullOrWhiteSpace(_selectedZip)) { MessageBox.Show(this, "Выберите ZIP-архив сборки.", "Не выбран файл", MessageBoxButtons.OK, MessageBoxIcon.Warning); return; }
            if (string.IsNullOrWhiteSpace(_token.Text)) { MessageBox.Show(this, "Введите GitHub Personal Access Token.", "Нет токена", MessageBoxButtons.OK, MessageBoxIcon.Warning); return; }
            try
            {
                _publish.Enabled = false; _status.Text = "Создание GitHub Release…";
                var info = string.Join(Environment.NewLine, new[] { "# Generated by Veles Build Publisher", "BUILD_NAME=" + _name.Text, "BUILD_VERSION=" + _version.Text, "MINECRAFT_VERSION=" + _minecraft.Text, "MOD_LOADER=" + _loader.Text, "MOD_LOADER_VERSION=" + _loaderVersion.Text, "SERVER_IP=" + _ip.Text, "SERVER_PORT=" + _port.Text, "SERVER_NAME=" + _serverName.Text, "SITE_URL=" + _site.Text, "LAUNCH_COMMAND=" + _launchCommand.Text }) + Environment.NewLine;
                var temp = Path.Combine(Path.GetTempPath(), "veles-build-info-" + Guid.NewGuid().ToString("N") + ".txt"); File.WriteAllText(temp, info);
                var api = new GitHubClient("kutsandriy14-cyber", "veles-modpack-releases", _token.Text);
                var tag = "build-" + _version.Text.Trim().TrimStart('v', 'V'); var release = await api.CreateReleaseAsync(tag, _name.Text + " v" + _version.Text, "Опубликовано через Veles Build Publisher.", CancellationToken.None);
                _status.Text = "Загрузка build.zip…"; await api.UploadAssetAsync(release.UploadUrl, _selectedZip, "build.zip", null, CancellationToken.None); _status.Text = "Загрузка build-info.txt…"; await api.UploadAssetAsync(release.UploadUrl, temp, "build-info.txt", null, CancellationToken.None); try { File.Delete(temp); } catch { }
                _status.Text = "Готово: релиз " + tag + " опубликован."; MessageBox.Show(this, "Сборка опубликована в GitHub Releases.", "Готово", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception error) { _status.Text = "Ошибка публикации."; MessageBox.Show(this, error.Message, "Ошибка", MessageBoxButtons.OK, MessageBoxIcon.Error); }
            finally { _publish.Enabled = true; }
        }
        private static Label Label(string text, int x, int y, float size, FontStyle style, Color color) { return new Label { Text = text, AutoSize = true, Location = new Point(x, y), Font = new Font("Segoe UI", size, style), ForeColor = color }; }
        private static TextBox Text(string value, int x, int y, int width) { return new TextBox { Text = value, Location = new Point(x, y), Width = width, Height = 28, BackColor = Color.FromArgb(15, 12, 11), ForeColor = Color.White, BorderStyle = BorderStyle.FixedSingle }; }
        private static Button Button(string text, int x, int y, int width, Color background, Color foreground) { return new Button { Text = text, Location = new Point(x, y), Width = width, Height = 30, BackColor = background, ForeColor = foreground, FlatStyle = FlatStyle.Flat, Font = new Font("Segoe UI", 9, FontStyle.Bold) }; }
    }
}
